minimum_pre_commit_version: "3.0.0"
default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: chisel-prettier
        name: Chisel Prettier
        entry: bun run prettier --write --ignore-unknown
        language: system
        files: \.(css|html|js|jsx|json|jsonc|md|mjs|mts|ts|tsx|yaml|yml)$

      - id: chisel-check
        name: Chisel checks
        entry: bun run check
        language: system
        pass_filenames: false
        files: \.(css|html|js|jsx|json|jsonc|md|mjs|mts|ts|tsx|yaml|yml)$
