"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GAME_DATA_EXPORT_ROOT = void 0;
exports.createGodotExportBundle = createGodotExportBundle;
exports.GAME_DATA_EXPORT_ROOT = "game_data";
function pascalCase(value) {
    const words = value.match(/[A-Za-z0-9]+/g) ?? [];
    const name = words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`).join("");
    return name || "Table";
}
function constantCase(value) {
    const words = value.match(/[A-Za-z0-9]+/g) ?? [];
    const name = words.map((word) => word.toUpperCase()).join("_");
    return /^[A-Z]/.test(name) ? name : `COLUMN_${name || "VALUE"}`;
}
function columnConstantNames(columns) {
    const nextSuffixByBase = new Map();
    const usedNames = new Set();
    const namesByColumnId = new Map();
    for (const column of columns) {
        const baseName = constantCase(column.name);
        let suffix = nextSuffixByBase.get(baseName) ?? 1;
        let name = suffix === 1 ? baseName : `${baseName}_${suffix}`;
        while (usedNames.has(name)) {
            suffix += 1;
            name = `${baseName}_${suffix}`;
        }
        nextSuffixByBase.set(baseName, suffix + 1);
        usedNames.add(name);
        namesByColumnId.set(column.id, name);
    }
    return namesByColumnId;
}
function gdString(value) {
    return JSON.stringify(value);
}
function gdValue(value, depth = 0) {
    if (value === null || typeof value === "undefined") {
        return "null";
    }
    if (typeof value === "string") {
        return gdString(value);
    }
    if (typeof value === "number") {
        return Number.isFinite(value) ? String(value) : "0";
    }
    if (typeof value === "boolean") {
        return value ? "true" : "false";
    }
    if (Array.isArray(value)) {
        return `[${value.map((entry) => gdValue(entry, depth)).join(", ")}]`;
    }
    if (typeof value === "object") {
        return gdDictionary(value, depth);
    }
    return gdString(String(value));
}
function gdDictionary(record, depth) {
    const entries = Object.entries(record);
    if (entries.length === 0) {
        return "{}";
    }
    const indent = "\t".repeat(depth);
    const innerIndent = "\t".repeat(depth + 1);
    const lines = entries.map(([key, value]) => `${innerIndent}${gdString(key)}: ${gdValue(value, depth + 1)}`);
    return `{\n${lines.join(",\n")}\n${indent}}`;
}
function columnValue(row, column) {
    const value = row.values.find((entry) => entry.columnId === column.id);
    return value?.value ?? column.defaultValue;
}
function enumBody(table) {
    if (table.rows.length === 0) {
        return "{}";
    }
    const lines = table.rows.map((row, index) => `\t${row.slug} = ${index}`);
    return `{\n${lines.join(",\n")}\n}`;
}
function slugsArray(table) {
    if (table.rows.length === 0) {
        return "[]";
    }
    return `[\n${table.rows.map((row) => `\t${gdString(row.slug)}`).join(",\n")}\n]`;
}
function columnArray(table, column) {
    if (table.rows.length === 0) {
        return "[]";
    }
    return `[\n${table.rows.map((row) => `\t${gdValue(columnValue(row, column))}`).join(",\n")}\n]`;
}
function columnArrays(table) {
    if (table.columns.length === 0) {
        return "";
    }
    const namesByColumnId = columnConstantNames(table.columns);
    return `\n${table.columns
        .map((column) => `const ${namesByColumnId.get(column.id) ?? constantCase(column.name)} := ${columnArray(table, column)}`)
        .join("\n")}`;
}
function tableClassName(table) {
    return `Chisel${pascalCase(table.id)}`;
}
function tablePath(table) {
    return `${exports.GAME_DATA_EXPORT_ROOT}/tables/${table.id}.gd`;
}
function renderTable(table) {
    const className = tableClassName(table);
    return {
        className,
        content: `# Generated by Chisel. Do not edit.\nclass_name ${className}\nextends RefCounted\n\nenum Id ${enumBody(table)}\n\nconst TABLE_ID := ${gdString(table.id)}\nconst TABLE_NAME := ${gdString(table.name)}\nconst TABLE_KIND := ${gdString(table.kind)}\nconst SLUGS := ${slugsArray(table)}${columnArrays(table)}\n`,
        path: tablePath(table),
        table
    };
}
function renderManifest(project, exportedAt, tables) {
    const entries = tables.map((entry) => `\t${gdString(entry.table.id)}: {\n\t\t"name": ${gdString(entry.table.name)},\n\t\t"class_name": ${gdString(entry.className)},\n\t\t"path": ${gdString(`res://${entry.path}`)},\n\t\t"rows": ${entry.table.rows.length},\n\t\t"columns": ${entry.table.columns.length}\n\t}`);
    return {
        content: `# Generated by Chisel. Do not edit.\nclass_name ChiselGameDataManifest\nextends RefCounted\n\nconst GENERATED_AT := ${gdString(exportedAt)}\nconst PROJECT_ID := ${gdString(project.id)}\nconst PROJECT_NAME := ${gdString(project.name)}\nconst TABLES := {\n${entries.join(",\n")}\n}\n`,
        path: `${exports.GAME_DATA_EXPORT_ROOT}/manifest.gd`
    };
}
function createGodotExportBundle(project, tables, exportedAt) {
    const tableFiles = tables.map(renderTable);
    return {
        files: [renderManifest(project, exportedAt, tableFiles), ...tableFiles.map(({ content, path }) => ({ content, path }))]
    };
}
