import type { AnyDataTable, DataColumnDefinition, DataTableRow, Project } from "./schemas";
import { InputKeyEnum } from "./types";

export const GAME_DATA_EXPORT_ROOT = "game_data";
const INPUT_BINDINGS_TABLE_ID = "input_bindings";

interface GodotTableExport {
  className: string;
  content: string;
  path: string;
  table: AnyDataTable;
}

export interface GodotExportFile {
  content: string;
  path: string;
}

export interface GodotExportBundle {
  files: GodotExportFile[];
}

function pascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const name = words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`).join("");
  return name || "Table";
}

function constantCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const name = words.map((word) => word.toUpperCase()).join("_");
  return /^[A-Z]/.test(name) ? name : `COLUMN_${name || "VALUE"}`;
}

function columnConstantNames(columns: DataColumnDefinition[]): Map<string, string> {
  const nextSuffixByBase = new Map<string, number>();
  const usedNames = new Set<string>();
  const namesByColumnId = new Map<string, string>();

  for (const column of columns) {
    const baseName = constantCase(column.name);
    let suffix = nextSuffixByBase.get(baseName) ?? 1;
    let name = suffix === 1 ? baseName : `${baseName}_${suffix}`;

    while (usedNames.has(name)) {
      suffix += 1;
      name = `${baseName}_${suffix}`;
    }

    nextSuffixByBase.set(baseName, suffix + 1);
    usedNames.add(name);
    namesByColumnId.set(column.id, name);
  }

  return namesByColumnId;
}

function gdString(value: string): string {
  return JSON.stringify(value);
}

function gdValue(value: unknown, depth = 0): string {
  if (value === null || typeof value === "undefined") {
    return "null";
  }
  if (typeof value === "string") {
    return gdString(value);
  }
  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "0";
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (Array.isArray(value)) {
    return `[${value.map((entry) => gdValue(entry, depth)).join(", ")}]`;
  }
  if (typeof value === "object") {
    return gdDictionary(value as Record<string, unknown>, depth);
  }
  return gdString(String(value));
}

function gdDictionary(record: Record<string, unknown>, depth: number): string {
  const entries = Object.entries(record);
  if (entries.length === 0) {
    return "{}";
  }
  const indent = "\t".repeat(depth);
  const innerIndent = "\t".repeat(depth + 1);
  const lines = entries.map(([key, value]) => `${innerIndent}${gdString(key)}: ${gdValue(value, depth + 1)}`);
  return `{\n${lines.join(",\n")}\n${indent}}`;
}

function columnValue(row: DataTableRow, column: DataColumnDefinition): unknown {
  const value = row.values.find((entry) => entry.columnId === column.id);
  return value?.value ?? column.defaultValue;
}

function enumBody(table: AnyDataTable): string {
  if (table.rows.length === 0) {
    return "{}";
  }
  const lines = table.rows.map((row, index) => `\t${row.slug} = ${index}`);
  return `{\n${lines.join(",\n")}\n}`;
}

function slugsArray(table: AnyDataTable): string {
  if (table.rows.length === 0) {
    return "[]";
  }
  return `[\n${table.rows.map((row) => `\t${gdString(row.slug)}`).join(",\n")}\n]`;
}

function columnArray(table: AnyDataTable, column: DataColumnDefinition): string {
  if (table.rows.length === 0) {
    return "[]";
  }
  return `[\n${table.rows.map((row) => `\t${gdValue(columnValue(row, column))}`).join(",\n")}\n]`;
}

function columnArrays(table: AnyDataTable): string {
  if (table.columns.length === 0) {
    return "";
  }
  const namesByColumnId = columnConstantNames(table.columns);
  return `\n${table.columns
    .map((column) => `const ${namesByColumnId.get(column.id) ?? constantCase(column.name)} := ${columnArray(table, column)}`)
    .join("\n")}`;
}

function tableClassName(table: AnyDataTable): string {
  return `Chisel${pascalCase(table.id)}`;
}

function tablePath(table: AnyDataTable): string {
  return `${GAME_DATA_EXPORT_ROOT}/tables/${table.id}.gd`;
}

function renderTable(table: AnyDataTable): GodotTableExport {
  const className = tableClassName(table);
  return {
    className,
    content: `# Generated by Chisel. Do not edit.\nclass_name ${className}\nextends RefCounted\n\nenum Id ${enumBody(table)}\n\nconst TABLE_ID := ${gdString(table.id)}\nconst TABLE_NAME := ${gdString(table.name)}\nconst TABLE_KIND := ${gdString(table.kind)}\nconst SLUGS := ${slugsArray(table)}${columnArrays(table)}\n`,
    path: tablePath(table),
    table
  };
}

function renderManifest(project: Project, exportedAt: string, tables: GodotTableExport[]): GodotExportFile {
  const entries = tables.map(
    (entry) =>
      `\t${gdString(entry.table.id)}: {\n\t\t"name": ${gdString(entry.table.name)},\n\t\t"class_name": ${gdString(entry.className)},\n\t\t"path": ${gdString(`res://${entry.path}`)},\n\t\t"rows": ${entry.table.rows.length},\n\t\t"columns": ${entry.table.columns.length}\n\t}`
  );

  return {
    content: `# Generated by Chisel. Do not edit.\nclass_name ChiselGameDataManifest\nextends RefCounted\n\nconst GENERATED_AT := ${gdString(exportedAt)}\nconst PROJECT_ID := ${gdString(project.id)}\nconst PROJECT_NAME := ${gdString(project.name)}\nconst TABLES := {\n${entries.join(",\n")}\n}\n`,
    path: `${GAME_DATA_EXPORT_ROOT}/manifest.gd`
  };
}

function inputBindingEventFactories(): string {
  const lines = Object.values(InputKeyEnum).map((binding) => {
    if (binding.startsWith("MOUSE_BUTTON_")) {
      return `\t\t${gdString(binding)}:\n\t\t\treturn _mouse_button(${binding})`;
    }
    return `\t\t${gdString(binding)}:\n\t\t\treturn _key(${binding})`;
  });
  return lines.join("\n");
}

function renderInputExport(tables: GodotTableExport[]): GodotExportFile[] {
  const inputTable = tables.find((entry) => entry.table.id === INPUT_BINDINGS_TABLE_ID);
  if (!inputTable) {
    return [];
  }

  return [
    {
      content: `# Generated by Chisel. Do not edit.\nclass_name ChiselInput\nextends RefCounted\n\nfunc apply_to_input_map(clear_existing: bool = true) -> void:\n\tfor index in range(ChiselInputBindings.SLUGS.size()):\n\t\tvar action_name := String(ChiselInputBindings.ACTION[index])\n\t\tif action_name.is_empty():\n\t\t\taction_name = String(ChiselInputBindings.SLUGS[index]).to_lower()\n\t\tif not InputMap.has_action(action_name):\n\t\t\tInputMap.add_action(action_name)\n\t\telif clear_existing:\n\t\t\tInputMap.action_erase_events(action_name)\n\t\tfor binding in ChiselInputBindings.BINDINGS[index]:\n\t\t\tvar event: Variant = _event_from_binding(String(binding))\n\t\t\tif event is InputEvent:\n\t\t\t\tInputMap.action_add_event(action_name, event)\n\nfunc _event_from_binding(binding: String) -> Variant:\n\tmatch binding:\n${inputBindingEventFactories()}\n\t\t_:\n\t\t\tpush_warning("Unsupported Chisel input binding: %s" % binding)\n\t\t\treturn null\n\nfunc _key(keycode: int) -> InputEventKey:\n\tvar event := InputEventKey.new()\n\tevent.keycode = keycode\n\treturn event\n\nfunc _mouse_button(button_index: int) -> InputEventMouseButton:\n\tvar event := InputEventMouseButton.new()\n\tevent.button_index = button_index\n\treturn event\n`,
      path: `${GAME_DATA_EXPORT_ROOT}/input.gd`
    }
  ];
}

export function createGodotExportBundle(project: Project, tables: AnyDataTable[], exportedAt: string): GodotExportBundle {
  const tableFiles = tables.map(renderTable);
  return {
    files: [
      renderManifest(project, exportedAt, tableFiles),
      ...renderInputExport(tableFiles),
      ...tableFiles.map(({ content, path }) => ({ content, path }))
    ]
  };
}
