import { snakeCase } from "lodash";
import type { AnyDataTable, DataColumnDefinition, DataTableRow } from "./schemas";
import { ColumnType } from "./types";

const INPUT_BINDINGS_TABLE_ID = "input_bindings";
const INPUT_BINDINGS_COLUMN_NAME = "bindings";

export interface HaxeFlixelInputExportFile {
  content: string;
  path: string;
}

const keyNamesByBinding: Readonly<Record<string, string>> = {
  KEY_0: "ZERO",
  KEY_1: "ONE",
  KEY_2: "TWO",
  KEY_3: "THREE",
  KEY_4: "FOUR",
  KEY_5: "FIVE",
  KEY_6: "SIX",
  KEY_7: "SEVEN",
  KEY_8: "EIGHT",
  KEY_9: "NINE",
  KEY_ALT: "ALT",
  KEY_BACKSPACE: "BACKSPACE",
  KEY_CTRL: "CONTROL",
  KEY_DOWN: "DOWN",
  KEY_ENTER: "ENTER",
  KEY_EQUAL: "PLUS",
  KEY_ESCAPE: "ESCAPE",
  KEY_F1: "F1",
  KEY_F2: "F2",
  KEY_F3: "F3",
  KEY_F4: "F4",
  KEY_F5: "F5",
  KEY_F6: "F6",
  KEY_F7: "F7",
  KEY_F8: "F8",
  KEY_F9: "F9",
  KEY_F10: "F10",
  KEY_F11: "F11",
  KEY_F12: "F12",
  KEY_KP_ADD: "NUMPADPLUS",
  KEY_KP_SUBTRACT: "NUMPADMINUS",
  KEY_LEFT: "LEFT",
  KEY_MINUS: "MINUS",
  KEY_RIGHT: "RIGHT",
  KEY_SHIFT: "SHIFT",
  KEY_SPACE: "SPACE",
  KEY_TAB: "TAB",
  KEY_UP: "UP"
};

const mouseNamesByBinding: Readonly<Record<string, string>> = {
  MOUSE_BUTTON_LEFT: "LEFT",
  MOUSE_BUTTON_MIDDLE: "MIDDLE",
  MOUSE_BUTTON_RIGHT: "RIGHT",
  MOUSE_BUTTON_WHEEL_DOWN: "WHEEL_DOWN",
  MOUSE_BUTTON_WHEEL_UP: "WHEEL_UP"
};

function pascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const result = words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`).join("");
  return /^[A-Z]/.test(result) ? result : `Data${result || "Table"}`;
}

function tableClassName(table: AnyDataTable): string {
  return `Chisel${pascalCase(table.name || table.id)}`;
}

function haxeString(value: string): string {
  return JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function columnValue(row: DataTableRow, column: DataColumnDefinition): unknown {
  return row.values.find((entry) => entry.columnId === column.id)?.value ?? column.defaultValue;
}

function bindingColumn(table: AnyDataTable): DataColumnDefinition {
  const column = table.columns.find((entry) => entry.name === INPUT_BINDINGS_COLUMN_NAME);
  if (!column || column.type !== ColumnType.enumArray) {
    throw new Error(`HaxeFlixel input export requires an enumArray column named "${INPUT_BINDINGS_COLUMN_NAME}".`);
  }
  return column;
}

function rowBindings(row: DataTableRow, column: DataColumnDefinition): string[] {
  const value = columnValue(row, column);
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) {
    throw new Error(`HaxeFlixel input action "${row.slug}" has invalid bindings.`);
  }
  return value;
}

function keyExpression(binding: string): string | undefined {
  const letter = /^KEY_([A-Z])$/.exec(binding)?.[1];
  const keyName = letter ?? keyNamesByBinding[binding];
  return keyName ? `FlxKey.${keyName}` : undefined;
}

function inputArrays(table: AnyDataTable): { keyboard: string[]; mouse: string[] } {
  const column = bindingColumn(table);
  const keyboard: string[] = [];
  const mouse: string[] = [];

  for (const row of table.rows) {
    const keyboardBindings: string[] = [];
    const mouseBindings: string[] = [];
    for (const binding of rowBindings(row, column)) {
      const key = keyExpression(binding);
      const mouseName = mouseNamesByBinding[binding];
      if (key) {
        keyboardBindings.push(key);
      } else if (mouseName) {
        mouseBindings.push(`ChiselMouseBinding.${mouseName}`);
      } else {
        throw new Error(`Unsupported HaxeFlixel input binding "${binding}" on action "${row.slug}".`);
      }
    }
    keyboard.push(`[${keyboardBindings.join(", ")}]`);
    mouse.push(`[${mouseBindings.join(", ")}]`);
  }

  return { keyboard, mouse };
}

export function renderHaxeFlixelInputExport(tables: AnyDataTable[], sourceRoot: string): HaxeFlixelInputExportFile[] {
  const inputTable = tables.find((table) => table.id === INPUT_BINDINGS_TABLE_ID);
  if (!inputTable) {
    return [];
  }

  const className = tableClassName(inputTable);
  const actionType = `${className}.${className}Id`;
  const actions = inputTable.rows.map((row) => haxeString(snakeCase(row.slug))).join(", ");
  const bindings = inputArrays(inputTable);

  return [
    {
      path: `${sourceRoot}/ChiselInput.hx`,
      content: `// Generated by Chisel. Do not edit.\npackage gamedata;\n\nimport flixel.FlxG;\nimport flixel.input.keyboard.FlxKey;\n\nprivate enum abstract ChiselMouseBinding(Int) {\n\tvar LEFT = 0;\n\tvar RIGHT = 1;\n\tvar MIDDLE = 2;\n\tvar WHEEL_UP = 3;\n\tvar WHEEL_DOWN = 4;\n}\n\nclass ChiselInput {\n\tpublic static final ACTION_NAMES:Array<String> = [${actions}];\n\tstatic final KEY_BINDINGS:Array<Array<FlxKey>> = [${bindings.keyboard.join(", ")}];\n\tstatic final MOUSE_BINDINGS:Array<Array<ChiselMouseBinding>> = [${bindings.mouse.join(", ")}];\n\n\tpublic static function actionName(action:${actionType}):String {\n\t\treturn ACTION_NAMES[actionIndex(action)];\n\t}\n\n\tpublic static function getActionStrength(action:${actionType}):Float {\n\t\treturn isActionPressed(action) ? 1.0 : 0.0;\n\t}\n\n\tpublic static function isActionPressed(action:${actionType}):Bool {\n\t\tfinal index = actionIndex(action);\n\t\t#if FLX_KEYBOARD\n\t\tif (FlxG.keys.anyPressed(KEY_BINDINGS[index])) {\n\t\t\treturn true;\n\t\t}\n\t\t#end\n\t\treturn hasPressedMouseBinding(MOUSE_BINDINGS[index]);\n\t}\n\n\tpublic static function isActionJustPressed(action:${actionType}):Bool {\n\t\tfinal index = actionIndex(action);\n\t\t#if FLX_KEYBOARD\n\t\tif (FlxG.keys.anyJustPressed(KEY_BINDINGS[index])) {\n\t\t\treturn true;\n\t\t}\n\t\t#end\n\t\treturn hasJustPressedMouseBinding(MOUSE_BINDINGS[index]);\n\t}\n\n\tpublic static function isActionJustReleased(action:${actionType}):Bool {\n\t\tfinal index = actionIndex(action);\n\t\t#if FLX_KEYBOARD\n\t\tif (FlxG.keys.anyJustReleased(KEY_BINDINGS[index])) {\n\t\t\treturn true;\n\t\t}\n\t\t#end\n\t\treturn hasJustReleasedMouseBinding(MOUSE_BINDINGS[index]);\n\t}\n\n\tstatic function actionIndex(action:${actionType}):Int {\n\t\tfinal index:Int = action;\n\t\tif (index < 0 || index >= ACTION_NAMES.length) {\n\t\t\tthrow 'Invalid Chisel input action: $index';\n\t\t}\n\t\treturn index;\n\t}\n\n\tstatic function hasPressedMouseBinding(bindings:Array<ChiselMouseBinding>):Bool {\n\t\tfor (binding in bindings) {\n\t\t\tif (isMousePressed(binding)) {\n\t\t\t\treturn true;\n\t\t\t}\n\t\t}\n\t\treturn false;\n\t}\n\n\tstatic function hasJustPressedMouseBinding(bindings:Array<ChiselMouseBinding>):Bool {\n\t\tfor (binding in bindings) {\n\t\t\tif (isMouseJustPressed(binding)) {\n\t\t\t\treturn true;\n\t\t\t}\n\t\t}\n\t\treturn false;\n\t}\n\n\tstatic function hasJustReleasedMouseBinding(bindings:Array<ChiselMouseBinding>):Bool {\n\t\tfor (binding in bindings) {\n\t\t\tif (isMouseJustReleased(binding)) {\n\t\t\t\treturn true;\n\t\t\t}\n\t\t}\n\t\treturn false;\n\t}\n\n\tstatic function isMousePressed(binding:ChiselMouseBinding):Bool {\n\t\t#if FLX_MOUSE\n\t\treturn switch (binding) {\n\t\t\tcase LEFT: FlxG.mouse.pressed;\n\t\t\tcase RIGHT:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.pressedRight;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase MIDDLE:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.pressedMiddle;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase WHEEL_UP: FlxG.mouse.wheel > 0;\n\t\t\tcase WHEEL_DOWN: FlxG.mouse.wheel < 0;\n\t\t};\n\t\t#else\n\t\treturn false;\n\t\t#end\n\t}\n\n\tstatic function isMouseJustPressed(binding:ChiselMouseBinding):Bool {\n\t\t#if FLX_MOUSE\n\t\treturn switch (binding) {\n\t\t\tcase LEFT: FlxG.mouse.justPressed;\n\t\t\tcase RIGHT:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.justPressedRight;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase MIDDLE:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.justPressedMiddle;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase WHEEL_UP: FlxG.mouse.wheel > 0;\n\t\t\tcase WHEEL_DOWN: FlxG.mouse.wheel < 0;\n\t\t};\n\t\t#else\n\t\treturn false;\n\t\t#end\n\t}\n\n\tstatic function isMouseJustReleased(binding:ChiselMouseBinding):Bool {\n\t\t#if FLX_MOUSE\n\t\treturn switch (binding) {\n\t\t\tcase LEFT: FlxG.mouse.justReleased;\n\t\t\tcase RIGHT:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.justReleasedRight;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase MIDDLE:\n\t\t\t\t#if FLX_MOUSE_ADVANCED\n\t\t\t\tFlxG.mouse.justReleasedMiddle;\n\t\t\t\t#else\n\t\t\t\tfalse;\n\t\t\t\t#end\n\t\t\tcase WHEEL_UP, WHEEL_DOWN: false;\n\t\t};\n\t\t#else\n\t\treturn false;\n\t\t#end\n\t}\n}\n`
    }
  ];
}
