import type { AnyDataTable, DataColumnDefinition, DataTableRow } from "./schemas";
import { ColumnType } from "./types";

const INPUT_BINDINGS_TABLE_ID = "input_bindings";
const INPUT_BINDINGS_COLUMN_NAME = "bindings";

export interface MonoGameInputExportFile {
  content: string;
  path: string;
}

const keyNamesByBinding: Readonly<Record<string, string[]>> = {
  KEY_0: ["D0"],
  KEY_1: ["D1"],
  KEY_2: ["D2"],
  KEY_3: ["D3"],
  KEY_4: ["D4"],
  KEY_5: ["D5"],
  KEY_6: ["D6"],
  KEY_7: ["D7"],
  KEY_8: ["D8"],
  KEY_9: ["D9"],
  KEY_ALT: ["LeftAlt", "RightAlt"],
  KEY_BACKSPACE: ["Back"],
  KEY_CTRL: ["LeftControl", "RightControl"],
  KEY_DOWN: ["Down"],
  KEY_ENTER: ["Enter"],
  KEY_EQUAL: ["OemPlus"],
  KEY_ESCAPE: ["Escape"],
  KEY_F1: ["F1"],
  KEY_F2: ["F2"],
  KEY_F3: ["F3"],
  KEY_F4: ["F4"],
  KEY_F5: ["F5"],
  KEY_F6: ["F6"],
  KEY_F7: ["F7"],
  KEY_F8: ["F8"],
  KEY_F9: ["F9"],
  KEY_F10: ["F10"],
  KEY_F11: ["F11"],
  KEY_F12: ["F12"],
  KEY_KP_ADD: ["Add"],
  KEY_KP_SUBTRACT: ["Subtract"],
  KEY_LEFT: ["Left"],
  KEY_MINUS: ["OemMinus"],
  KEY_RIGHT: ["Right"],
  KEY_SHIFT: ["LeftShift", "RightShift"],
  KEY_SPACE: ["Space"],
  KEY_TAB: ["Tab"],
  KEY_UP: ["Up"]
};

const mouseNamesByBinding: Readonly<Record<string, string>> = {
  MOUSE_BUTTON_LEFT: "Left",
  MOUSE_BUTTON_MIDDLE: "Middle",
  MOUSE_BUTTON_RIGHT: "Right",
  MOUSE_BUTTON_WHEEL_DOWN: "WheelDown",
  MOUSE_BUTTON_WHEEL_UP: "WheelUp"
};

function pascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const result = words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`).join("");
  return /^[A-Z]/.test(result) ? result : `Data${result || "Table"}`;
}

function tableClassName(table: AnyDataTable): string {
  return `Chisel${pascalCase(table.name || table.id)}`;
}

function csharpString(value: string): string {
  return JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function columnValue(row: DataTableRow, column: DataColumnDefinition): unknown {
  return row.values.find((entry) => entry.columnId === column.id)?.value ?? column.defaultValue;
}

function bindingColumn(table: AnyDataTable): DataColumnDefinition {
  const column = table.columns.find((entry) => entry.name === INPUT_BINDINGS_COLUMN_NAME);
  if (!column || column.type !== ColumnType.enumArray) {
    throw new Error(`MonoGame input export requires an enumArray column named "${INPUT_BINDINGS_COLUMN_NAME}".`);
  }
  return column;
}

function rowBindings(row: DataTableRow, column: DataColumnDefinition): string[] {
  const value = columnValue(row, column);
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) {
    throw new Error(`MonoGame input action "${row.slug}" has invalid bindings.`);
  }
  return value;
}

function keyExpressions(binding: string): string[] | undefined {
  const letter = /^KEY_([A-Z])$/.exec(binding)?.[1];
  const names = letter ? [letter] : keyNamesByBinding[binding];
  return names?.map((name) => `Keys.${name}`);
}

function inputArrays(table: AnyDataTable): { keyboard: string[]; mouse: string[] } {
  const column = bindingColumn(table);
  const keyboard: string[] = [];
  const mouse: string[] = [];

  for (const row of table.rows) {
    const keyboardBindings: string[] = [];
    const mouseBindings: string[] = [];
    for (const binding of rowBindings(row, column)) {
      const keys = keyExpressions(binding);
      const mouseName = mouseNamesByBinding[binding];
      if (keys) {
        keyboardBindings.push(...keys);
      } else if (mouseName) {
        mouseBindings.push(`ChiselMouseBinding.${mouseName}`);
      } else {
        throw new Error(`Unsupported MonoGame input binding "${binding}" on action "${row.slug}".`);
      }
    }
    keyboard.push(`new Keys[] { ${keyboardBindings.join(", ")} }`);
    mouse.push(`new ChiselMouseBinding[] { ${mouseBindings.join(", ")} }`);
  }

  return { keyboard, mouse };
}

export function renderMonoGameInputExport(tables: AnyDataTable[], sourceRoot: string): MonoGameInputExportFile[] {
  const inputTable = tables.find((table) => table.id === INPUT_BINDINGS_TABLE_ID);
  if (!inputTable) {
    return [];
  }

  const actionType = `${tableClassName(inputTable)}Id`;
  const actions = inputTable.rows.map((row) => csharpString(row.slug.toLowerCase())).join(", ");
  const bindings = inputArrays(inputTable);

  return [
    {
      path: `${sourceRoot}/ChiselInput.g.cs`,
      content: `// <auto-generated />
// Generated by Chisel. Do not edit.
using System;
using Microsoft.Xna.Framework.Input;

namespace Chisel.Generated
{
    internal enum ChiselMouseBinding
    {
        Left,
        Right,
        Middle,
        WheelUp,
        WheelDown
    }

    public sealed class ChiselInput
    {
        public static readonly string[] ActionNames = new string[] { ${actions} };
        private static readonly Keys[][] KeyBindings = new Keys[][] { ${bindings.keyboard.join(", ")} };
        private static readonly ChiselMouseBinding[][] MouseBindings = new ChiselMouseBinding[][] { ${bindings.mouse.join(", ")} };

        private KeyboardState _currentKeyboard;
        private KeyboardState _previousKeyboard;
        private MouseState _currentMouse;
        private MouseState _previousMouse;
        private bool _hasState;

        public void Update()
        {
            Update(Keyboard.GetState(), Mouse.GetState());
        }

        public void Update(KeyboardState keyboard, MouseState mouse)
        {
            if (!_hasState)
            {
                _previousKeyboard = keyboard;
                _previousMouse = mouse;
                _hasState = true;
            }
            else
            {
                _previousKeyboard = _currentKeyboard;
                _previousMouse = _currentMouse;
            }

            _currentKeyboard = keyboard;
            _currentMouse = mouse;
        }

        public string ActionName(${actionType} action)
        {
            return ActionNames[ActionIndex(action)];
        }

        public float GetActionStrength(${actionType} action)
        {
            return IsActionPressed(action) ? 1.0f : 0.0f;
        }

        public bool IsActionPressed(${actionType} action)
        {
            EnsureUpdated();
            int index = ActionIndex(action);
            return HasPressedKey(KeyBindings[index]) || HasPressedMouseBinding(MouseBindings[index]);
        }

        public bool IsActionJustPressed(${actionType} action)
        {
            EnsureUpdated();
            int index = ActionIndex(action);
            return HasJustPressedKey(KeyBindings[index]) || HasJustPressedMouseBinding(MouseBindings[index]);
        }

        public bool IsActionJustReleased(${actionType} action)
        {
            EnsureUpdated();
            int index = ActionIndex(action);
            return HasJustReleasedKey(KeyBindings[index]) || HasJustReleasedMouseBinding(MouseBindings[index]);
        }

        private static int ActionIndex(${actionType} action)
        {
            int index = (int)action;
            if (index < 0 || index >= ActionNames.Length)
            {
                throw new ArgumentOutOfRangeException(nameof(action), action, "Invalid Chisel input action.");
            }
            return index;
        }

        private void EnsureUpdated()
        {
            if (!_hasState)
            {
                throw new InvalidOperationException("Call ChiselInput.Update() once per game update before querying actions.");
            }
        }

        private bool HasPressedKey(Keys[] bindings)
        {
            foreach (Keys binding in bindings)
            {
                if (_currentKeyboard.IsKeyDown(binding))
                {
                    return true;
                }
            }
            return false;
        }

        private bool HasJustPressedKey(Keys[] bindings)
        {
            foreach (Keys binding in bindings)
            {
                if (_currentKeyboard.IsKeyDown(binding) && _previousKeyboard.IsKeyUp(binding))
                {
                    return true;
                }
            }
            return false;
        }

        private bool HasJustReleasedKey(Keys[] bindings)
        {
            foreach (Keys binding in bindings)
            {
                if (_currentKeyboard.IsKeyUp(binding) && _previousKeyboard.IsKeyDown(binding))
                {
                    return true;
                }
            }
            return false;
        }

        private bool HasPressedMouseBinding(ChiselMouseBinding[] bindings)
        {
            foreach (ChiselMouseBinding binding in bindings)
            {
                if (IsMousePressed(binding, _currentMouse))
                {
                    return true;
                }
            }
            return false;
        }

        private bool HasJustPressedMouseBinding(ChiselMouseBinding[] bindings)
        {
            foreach (ChiselMouseBinding binding in bindings)
            {
                if (IsMouseJustPressed(binding))
                {
                    return true;
                }
            }
            return false;
        }

        private bool HasJustReleasedMouseBinding(ChiselMouseBinding[] bindings)
        {
            foreach (ChiselMouseBinding binding in bindings)
            {
                if (IsMouseJustReleased(binding))
                {
                    return true;
                }
            }
            return false;
        }

        private bool IsMouseJustPressed(ChiselMouseBinding binding)
        {
            if (binding == ChiselMouseBinding.WheelUp)
            {
                return _currentMouse.ScrollWheelValue > _previousMouse.ScrollWheelValue;
            }
            if (binding == ChiselMouseBinding.WheelDown)
            {
                return _currentMouse.ScrollWheelValue < _previousMouse.ScrollWheelValue;
            }
            return IsMousePressed(binding, _currentMouse) && !IsMousePressed(binding, _previousMouse);
        }

        private bool IsMouseJustReleased(ChiselMouseBinding binding)
        {
            if (binding == ChiselMouseBinding.WheelUp || binding == ChiselMouseBinding.WheelDown)
            {
                return false;
            }
            return !IsMousePressed(binding, _currentMouse) && IsMousePressed(binding, _previousMouse);
        }

        private bool IsMousePressed(ChiselMouseBinding binding, MouseState state)
        {
            switch (binding)
            {
                case ChiselMouseBinding.Left:
                    return state.LeftButton == ButtonState.Pressed;
                case ChiselMouseBinding.Right:
                    return state.RightButton == ButtonState.Pressed;
                case ChiselMouseBinding.Middle:
                    return state.MiddleButton == ButtonState.Pressed;
                case ChiselMouseBinding.WheelUp:
                    return _currentMouse.ScrollWheelValue > _previousMouse.ScrollWheelValue;
                case ChiselMouseBinding.WheelDown:
                    return _currentMouse.ScrollWheelValue < _previousMouse.ScrollWheelValue;
                default:
                    throw new ArgumentOutOfRangeException(nameof(binding), binding, "Unknown Chisel mouse binding.");
            }
        }
    }
}
`
    }
  ];
}
