export type { Asset } from "./schemas";

export interface FileMetadata {
  sourcePath: string;
  fileName: string;
  stem: string;
  extension: string;
  sizeBytes: number;
  createdAt: string;
  modifiedAt: string;
  isImage: boolean;
  format?: string;
  width?: number;
  height?: number;
}

export enum AssetCategoryEnum {
  image = "image",
  audio = "audio",
  font = "font",
  data = "data",
  other = "other"
}
export const assetCategoryLabelMap: Record<AssetCategoryEnum, string> = {
  [AssetCategoryEnum.image]: "Image",
  [AssetCategoryEnum.audio]: "Audio",
  [AssetCategoryEnum.font]: "Font",
  [AssetCategoryEnum.data]: "Data",
  [AssetCategoryEnum.other]: "Other"
};

export const assetCategoryOptionValues = Object.values(AssetCategoryEnum).map((category) => ({
  label: assetCategoryLabelMap[category],
  value: category
}));

export type AssetCategory = `${AssetCategoryEnum}`;

export enum InputKeyEnum {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  H = "H",
  I = "I",
  J = "J",
  K = "K",
  L = "L",
  M = "M",
  N = "N",
  O = "O",
  P = "P",
  Q = "Q",
  R = "R",
  S = "S",
  T = "T",
  U = "U",
  V = "V",
  W = "W",
  X = "X",
  Y = "Y",
  Z = "Z",
  Digit0 = "0",
  Digit1 = "1",
  Digit2 = "2",
  Digit3 = "3",
  Digit4 = "4",
  Digit5 = "5",
  Digit6 = "6",
  Digit7 = "7",
  Digit8 = "8",
  Digit9 = "9",
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",
  F13 = "F13",
  F14 = "F14",
  F15 = "F15",
  F16 = "F16",
  F17 = "F17",
  F18 = "F18",
  F19 = "F19",
  F20 = "F20",
  F21 = "F21",
  F22 = "F22",
  F23 = "F23",
  F24 = "F24",
  Return = "Return",
  Escape = "Escape",
  Backspace = "Backspace",
  Tab = "Tab",
  Space = "Space",
  Minus = "-",
  Equal = "=",
  BracketLeft = "[",
  BracketRight = "]",
  Backslash = "\\",
  Hash = "#",
  Semicolon = ";",
  Quote = "'",
  Backquote = "`",
  Comma = ",",
  Period = ".",
  Slash = "/",
  CapsLock = "CapsLock",
  PrintScreen = "PrintScreen",
  ScrollLock = "ScrollLock",
  Pause = "Pause",
  Insert = "Insert",
  Home = "Home",
  PageUp = "PageUp",
  Delete = "Delete",
  End = "End",
  PageDown = "PageDown",
  Right = "Right",
  Left = "Left",
  Down = "Down",
  Up = "Up",
  Numlock = "Numlock",
  KeypadDivide = "Keypad /",
  KeypadMultiply = "Keypad *",
  KeypadMinus = "Keypad -",
  KeypadPlus = "Keypad +",
  KeypadEnter = "Keypad Enter",
  Keypad0 = "Keypad 0",
  Keypad1 = "Keypad 1",
  Keypad2 = "Keypad 2",
  Keypad3 = "Keypad 3",
  Keypad4 = "Keypad 4",
  Keypad5 = "Keypad 5",
  Keypad6 = "Keypad 6",
  Keypad7 = "Keypad 7",
  Keypad8 = "Keypad 8",
  Keypad9 = "Keypad 9",
  KeypadPeriod = "Keypad .",
  KeypadEqual = "Keypad =",
  KeypadComma = "Keypad ,",
  KeypadEqualAs400 = "Keypad = (AS400)",
  Keypad00 = "Keypad 00",
  Keypad000 = "Keypad 000",
  ThousandsSeparator = "ThousandsSeparator",
  DecimalSeparator = "DecimalSeparator",
  CurrencyUnit = "CurrencyUnit",
  CurrencySubUnit = "CurrencySubUnit",
  KeypadLeftParen = "Keypad (",
  KeypadRightParen = "Keypad )",
  KeypadLeftBrace = "Keypad {",
  KeypadRightBrace = "Keypad }",
  KeypadTab = "Keypad Tab",
  KeypadBackspace = "Keypad Backspace",
  KeypadA = "Keypad A",
  KeypadB = "Keypad B",
  KeypadC = "Keypad C",
  KeypadD = "Keypad D",
  KeypadE = "Keypad E",
  KeypadF = "Keypad F",
  KeypadXor = "Keypad XOR",
  KeypadPower = "Keypad ^",
  KeypadPercent = "Keypad %",
  KeypadLess = "Keypad <",
  KeypadGreater = "Keypad >",
  KeypadAmpersand = "Keypad &",
  KeypadDoubleAmpersand = "Keypad &&",
  KeypadPipe = "Keypad |",
  KeypadDoublePipe = "Keypad ||",
  KeypadColon = "Keypad :",
  KeypadHash = "Keypad #",
  KeypadSpace = "Keypad Space",
  KeypadAt = "Keypad @",
  KeypadExclamation = "Keypad !",
  KeypadMemStore = "Keypad MemStore",
  KeypadMemRecall = "Keypad MemRecall",
  KeypadMemClear = "Keypad MemClear",
  KeypadMemAdd = "Keypad MemAdd",
  KeypadMemSubtract = "Keypad MemSubtract",
  KeypadMemMultiply = "Keypad MemMultiply",
  KeypadMemDivide = "Keypad MemDivide",
  KeypadPlusMinus = "Keypad +/-",
  KeypadClear = "Keypad Clear",
  KeypadClearEntry = "Keypad ClearEntry",
  KeypadBinary = "Keypad Binary",
  KeypadOctal = "Keypad Octal",
  KeypadDecimal = "Keypad Decimal",
  KeypadHexadecimal = "Keypad Hexadecimal",
  NonUSBackslash = "NonUSBackslash",
  Application = "Application",
  Power = "Power",
  Execute = "Execute",
  Help = "Help",
  Menu = "Menu",
  Select = "Select",
  Stop = "Stop",
  Again = "Again",
  Undo = "Undo",
  Cut = "Cut",
  Copy = "Copy",
  Paste = "Paste",
  Find = "Find",
  Mute = "Mute",
  VolumeUp = "VolumeUp",
  VolumeDown = "VolumeDown",
  International1 = "International 1",
  International2 = "International 2",
  International3 = "International 3",
  International4 = "International 4",
  International5 = "International 5",
  International6 = "International 6",
  International7 = "International 7",
  International8 = "International 8",
  International9 = "International 9",
  Language1 = "Language 1",
  Language2 = "Language 2",
  Language3 = "Language 3",
  Language4 = "Language 4",
  Language5 = "Language 5",
  Language6 = "Language 6",
  Language7 = "Language 7",
  Language8 = "Language 8",
  Language9 = "Language 9",
  AltErase = "AltErase",
  SysReq = "SysReq",
  Cancel = "Cancel",
  Clear = "Clear",
  Prior = "Prior",
  Separator = "Separator",
  Out = "Out",
  Oper = "Oper",
  ClearAgain = "Clear / Again",
  CrSel = "CrSel",
  ExSel = "ExSel",
  LeftCtrl = "Left Ctrl",
  LeftShift = "Left Shift",
  LeftAlt = "Left Alt",
  LeftGui = "Left GUI",
  RightCtrl = "Right Ctrl",
  RightShift = "Right Shift",
  RightAlt = "Right Alt",
  RightGui = "Right GUI",
  ModeSwitch = "ModeSwitch",
  Sleep = "Sleep",
  Wake = "Wake",
  ChannelUp = "ChannelUp",
  ChannelDown = "ChannelDown",
  MediaPlay = "MediaPlay",
  MediaPause = "MediaPause",
  MediaRecord = "MediaRecord",
  MediaFastForward = "MediaFastForward",
  MediaRewind = "MediaRewind",
  MediaTrackNext = "MediaTrackNext",
  MediaTrackPrevious = "MediaTrackPrevious",
  MediaStop = "MediaStop",
  Eject = "Eject",
  MediaPlayPause = "MediaPlayPause",
  MediaSelect = "MediaSelect",
  AcNew = "AC New",
  AcOpen = "AC Open",
  AcClose = "AC Close",
  AcExit = "AC Exit",
  AcSave = "AC Save",
  AcPrint = "AC Print",
  AcProperties = "AC Properties",
  AcSearch = "AC Search",
  AcHome = "AC Home",
  AcBack = "AC Back",
  AcForward = "AC Forward",
  AcStop = "AC Stop",
  AcRefresh = "AC Refresh",
  AcBookmarks = "AC Bookmarks",
  SoftLeft = "SoftLeft",
  SoftRight = "SoftRight",
  Call = "Call",
  EndCall = "EndCall",
  MouseLeft = "MouseLeft",
  MouseRight = "MouseRight",
  MouseMiddle = "MouseMiddle",
  WheelUp = "WheelUp",
  WheelDown = "WheelDown"
}

export enum ColumnType {
  id = "id",
  string = "string",
  text = "text",
  integer = "integer",
  decimal = "decimal",
  range = "range",
  boolean = "boolean",
  enum = "enum",
  enumArray = "enumArray",
  assetRef = "assetRef",
  ref = "ref",
  color = "color",
  vector2 = "vector2",
  vector3 = "vector3",
  vector4 = "vector4",
  json = "json"
}
